blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [

	# www.mysite.com/
	path('', views.index,name='index'),

	# www.mysite.com/home
	path('home/', views.Home.as_view(),name='home'),

	# www.mysite.com/post/22/author?=name
	path('post/<int:pk>/author?=<str:author>/', views.DetailPost.as_view(),name='detail'),

	# www.mysite.com/new_post/
	path('new_post/', views.NewPost.as_view(),name='new_post'),

	# www.mysite.com/post/2?=delete/
	path('post/<int:pk>?=delete', views.DeletePost.as_view(),name='delete'),

	# www.mysite.com/post/2?=edit/
	path('post/<int:pk>?=edit', views.UpdatePost.as_view(),name='edit'),

	# www.mysite.com/home
	path('post/u<int:pk>/<str:name>/profile',views.UserPosts.as_view(),name='user_post'),
	
]

mydjangoblog/urls.py
from django.contrib import admin
from django.urls import path,include
from user import views as user_views
import django.contrib.auth.views as auth_views
from mydjangoblog import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # www.mysite.com/
    path('', include('blog.urls')),

    # www.mysite.com/register
    path('register/',user_views.register,name='register'),

    path('activate/<uidb64>/<token>', user_views.activate, name='activate'),

    # www.mysite.com/login
    path('login/', auth_views.LoginView.as_view(template_name="user/login.html"),
    	name="login"),

    # www.mysite.com/logout
    path('logout/', auth_views.LogoutView.as_view(template_name="user/logout.html"),
    	name="logout"),

    #www.mysite.com/profile
    path('profile/', user_views.profile,name='profile'),

    #www.mysite.com/profile_update
    path('profile_update/', user_views.profile_update,name='profile_update'),

    #www.mysite.com/password_reset
    path('password_reset/',auth_views.PasswordResetView.as_view(
    	template_name="user/password_reset.html"),name="password_reset"),

    #www.mysite.com/password_reset_done
    path('password_reset_done/',auth_views.PasswordResetDoneView.as_view(
    	template_name="user/password_reset_done.html"),name="password_reset_done"),

    #www.mysite.com/password_reset_confirm
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
    	template_name="user/password_reset_confirm.html"),name="password_reset_confirm"),

    #www.mysite.com/password_reset_complete
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
    	template_name="user/password_reset_complete.html"),name="password_reset_complete"),

]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.urls import reverse
User = get_user_model()


# Create your models here.


class Post(models.Model):
	title = models.CharField(max_length=100)
	content = models.TextField()
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	created_on = models.DateTimeField(auto_now=True)
	#tags = models.ManyToManyField(Tag)

	def get_absolute_url (self):
		return reverse('blog:detail',kwargs={"pk":self.pk,"author":self.author.first_name})

	def __str__(self):
		return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404,reverse
from django.views.generic import ListView,DetailView,CreateView,DeleteView,UpdateView
from .models import Post
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.urls import reverse_lazy
'''
from django.template import Library
from django.template.defaultfilters import stringfilter
from django.utils.html import conditional_escape
from django.utils.safestring import mark_safe
import re

register = Library()

@stringfilter
def spacify(value, autoescape=None):
	if autoescape:
		esc = conditional_escape
	else:
		esc = lambda x: x
	return mark_safe(re.sub("\s", '&'+'nbsp;', esc(value)))
spacify.needs_autoescape = True
register.filter(spacify)
'''
# Create your views here.
def index(request):
	return render(request, 'blog/index.html')


class Home(ListView):
	model = Post
	template_name = 'blog/home.html' #default_name = 'blog/post_list.html'
	context_object_name = 'post_list' #default_name = 'object_list'
	ordering = '-created_on'
	paginate_by = 10
	
class DetailPost(DetailView):
	model = Post
	context_object_name = 'post' #default = obj
	template_name = 'blog/post_detail.html' #default = 'blog/post_detail.html'

class NewPost(LoginRequiredMixin,CreateView):
	model = Post
	fields = ['title','content']
	template_name = 'blog/post_create.html'  # default = 'blog/post_form.html'
	context_object_name = 'form' # default = form 

	def form_valid(self,form):
		form.instance.author = self.request.user
		return super().form_valid(form)

class UpdatePost(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
	model = Post
	fields = ['title','content']
	template_name = 'blog/post_create.html'  # default = 'blog/post_form.html'
	context_object_name = 'form' # default = form 

	def test_func(self):
		post = self.get_object()
		if self.request.user == post.author:
			return True
		else :
			return False

	def form_valid(self,form):
		form.instance.author = self.request.user
		return super().form_valid(form)



class DeletePost(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
	model = Post
	template_name = 'blog/post_delete.html' #default = 'blog/post_delete.html'
	pk = None
	#success_url = '/' #reverse('blog:user_post',kwargs={'pk':pk})

	def get_success_url(self):
		user = self.request.user
		return reverse_lazy('blog:user_post',kwargs={"pk":user.pk,"name":user.first_name})





	def test_func(self):
		post = self.get_object()
		pk = self.request.user.pk
		if self.request.user == post.author:
			return True
		else :
			return False


class UserPosts(ListView):
	model = Post
	context_object_name='post_list' #default = 'object'
	template_name = 'blog/user_post.html'
	ordering = '-created_on'
	paginate_by = 10
	
	def get_context_data(self, **kwargs):
		# Call the base implementation first to get a context
		context = super().get_context_data(**kwargs)
		# Add in a QuerySet of all the books
		user = get_object_or_404(get_user_model(),pk=self.kwargs.get("pk"))
		context['author'] = user
		return context

	def get_queryset(self):
		user = get_object_or_404(get_user_model(),pk=self.kwargs.get("pk"))
		return Post.objects.filter(author = user)

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<!--Import Google Icons-->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!--Import materialize.css-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

<!-- Materialize CSS Offline
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/materialize.min.css' %}">
-->
<!-- Import Google Fonts -->
<link href="https://fonts.googleapis.com/css2?family=Sofia&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
<!--Import Custom CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}">


<!--Let browser know website is optimized for mobile-->
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>



<nav class="transparent">
	<div class="navbar-wrapper">
		<a href="/" class="brand-logo -text sofia center">Blog</a>
		<a href="" class="button-collapse " data-activates="sidenavbar" ><i class="material-icons black-text">menu</i></a>
		<ul class="right hide-on-med-and-down">
			<li><a href="{% url 'blog:home' %}" class="">Home</a></li>
			{% if user.is_authenticated %}
			<li><a href="{% url	'profile' %}" class="">profile</a></li>
			<li><a href="{% url 'blog:user_post' pk=user.pk name=user.first_name %}">
				My Posts</a>
			</li>
			<li><a href="{% url 'logout' %}" class="">Logout</a></li>
			{% else %}
			<li><a href="{% url 'login' %}" class="">LogIn</a></li>
			<li><a href="{% url 'register' %}" class="">Register</a></li>
			{% endif %}
		</ul>
		<ul class="side-nav" id="sidenavbar">
			{% if user.is_authenticated %}
			<div class="user-view">
				<div class="background">
					<img src="{% static 'blog/images/polygon.png' %}" class="responsive-img">
				</div>
				<a href=""><img src="{{user.profile.img.url}}" class="circle"></a>
				<span class="name black-text">{{user.first_name}} {{user.last_name}}</span>
				<span class="email cursive black-text">{{user.email}}</span>
			</div>
			<li><a href="{% url 'blog:home' %}" class="black-text">Home</a></li>
			<li><a href="{% url	'profile' %}" class="black-text">profile</a></li>
			<li><a href="{% url 'blog:user_post' pk=user.pk name=user.first_name %}">
				My Posts</a>
			</li>
			<li><a href="{% url 'logout' %}" class="black-text">Logout</a></li>
			{% else %}
			<li><a href="{% url 'blog:home' %}" class="black-text">Home</a></li>
			<li><a href="{% url 'login' %}" class="black-text">LogIn</a></li>
			<li><a href="{% url 'register' %}" class="black-text">Register</a></li>
			{% endif %}
		</ul>
	</div>
</nav>


{% block body %}

{% endblock %}



<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

<script src="https://kit.fontawesome.com/8806ff8ba0.js" crossorigin="anonymous"></script>
<!-- Offline 
<script type="text/javascript" src="{% static 'blog/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'blog/js/materialize.min.js' %}"></script>-->
<script>
    $('document').ready(function(){
        // jquery goes here
        $('.button-collapse').sideNav();

        $('.close-alert').click(function(){
			$( ".materialert" ).fadeOut( "slow");
		});

        $('.collapsible').collapsible();

    });
</script>
</body>
</html>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% block body %}


<div class="row">
	<div class="col l11 m12 s12 " style="height: fit-content;">
		<div class="row" style="margin-top: 10px;">
			{% for post in post_list %}
			<div class="col l6 m12 s12 ">
				<div class="card-panel rsp" style=" margin-top: 10px;" >
					<div class="row">
						<div class="col l4 m4 s12 center">
							<a href="{% url 'blog:user_post' pk=post.author.pk name=post.author.first_name %}">
							<img src="{{post.author.profile.img.url}}" class="circle responsive-img">
							</a>
						</div>
						<a href="{% url 'blog:detail' pk=post.pk author=post.author.first_name %}" class="black-text">
						<div class="col l8 m8 s12">
							
							<h4 class="center-align josefin flow-text">{{post.title}}</h4>
							<p class="truncate">{{post.content}}.</p>
							<p class="right-align cursive">Created on {{post.created_on}}</p>
							
						</div>
						</a>
					</div>				
				</div>
				
			</div>
			{% endfor %}
		</div>
	</div>
</div>












{% if user.is_authenticated %}
<div class="fixed-action-btn">
	<a href="{% url 'blog:new_post' %}" class="btn-floating btn-large white pulse">
		<i class="material-icons black-text tooltipped" data-tooltip="New Post" data-position="left">create</i>
	</a>
</div>
{% endif %}


{% if is_paginated %}
<div class="center">
	<ul class="pagination ">
		{% if page_obj.has_previous %}
			<li class="transparent ">
				<a href="?page={{page_obj.previous_page_number}}" class="circle white black-text">
					&lsaquo;
				</a>
			</li>
		{% endif %}
		{% for num in page_obj.paginator.page_range %}
			{% if page_obj.number == num %}
				<li class="active transparent">
					<a href="?page={{num}}" class="circle black white-text">{{num}}</a>
				</li>
			{% else %}
				<li class=" transparent black-text">
					<a href="?page={{num}}" class="circle white">{{num}}</a>
				</li>
			{% endif %}
		{% endfor %}
			{% if page_obj.has_next %}
			<li class="transparent ">
				<a href="?page={{page_obj.next_page_number}}" class="circle white black-text">
					&rsaquo;
				</a>
			</li>
		{% endif %}
	</ul>
</div>
{% endif %}


{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block body %}

<h1 class="sofia center-align home white-text">
Read, write and share awesome Blogs
</h1>	
<br><br>
{% if not user.is_authenticated %}
<h5 class="sofia white-text center-align">
<a href="{% url 'login' %}" class="white-text">SignIn</a> / <a href="{% url 'register' %}" class="white-text">SignUp</a>
</h5>
{% endif %}
<br><br>
<footer class="page-footer black" style="opacity: 0.9;">
	<div class="footer-copyright">
		<div class="container">
			All right Reserved &copy; 2020 Copyright
			<div class="right">
				<a href="https://www.linkedin.com/in/abhishek-vaish-b3195817a/" target="blank" style="margin-right: 10px;" class="white-text">
					<i class="fab fa-linkedin-in small"></i>
				</a>
				<a href="https://github.com/Abhishekvaish" target="blank" style="margin-right: 10px;" class="white-text">
					<i class="fab fa-github small"></i>
				</a>
				<a href="https://twitter.com/Abhishekvaish40" target="blank" style="margin-right: 10px;" class="white-text">
					<i class="fab fa-twitter small"></i>
				</a>
				<a href="https://mail.google.com/mail/u/0/?view=cm&fs=1&to=abhishek953566936222@gmail.com&tf=1" target="blank" class="white-text"><i class="fa fa-envelope small"></i>
				</a>
			</div>
		</div>
    </div>
</footer>
{% endblock %}

blog/templates/blog/post_create.html
{% extends 'blog/base.html' %}

{% block body %}

<div class="row">
	<div class="col l10 offset-l1 m12 s12 card-panel" style="opacity: 1;">
		<h3 class="center-align sofia">New Post</h3>
		<form method="post">
			{% csrf_token %}
				{% if form.non_field_errors %}
					    {% for err in form.non_field_errors %}
					      <p class="red-text">{{ err }}</p>
					    {% endfor %}
					{% endif %}
				<br>
				{% for field in form %}
					<div class="input-field center-align">
						{% if field.auto_id == 'id_content' %}
							<textarea name="content" required id="id_content" class="materialize-textarea cursive">{{field.value|default_if_none:"" }}</textarea>

						{% else %}
							{{field}}
						{% endif %}
					<label for="{{field.auto_id}}">{{field.label}}</label>
					</div>
				{% endfor %}
				<div class="center">
					<br>
					<button type="submit" class="btn">Post</button>
					<br><br>
				</div>
		</form>

	</div>
</div>

{% endblock %}

blog/templates/blog/post_delete.html
{% extends 'blog/base.html' %}
{% block body %}

<div class="row">
	<br>
	<div class="card-panel col s10 offset-s1 l6 offset-l3 z-depth-3 blue-grey lighten-5"> 
		<div class="col s9 offset-s1">
			<br>

			<form method="POST" >
				{% csrf_token %}	
				<br><br>
				<h4>Do You Really want to delete {{object.title}} ?</h4>
				<p>Note : You Won't be able to restore this post</p>
				<div class="center">
					<br>
					<a href="{% url 'blog:detail' pk=object.pk author=object.author.first_name %}"
					class="btn">No</a>
				<button class="btn waves-effect large red white-text" type="submit"><b>Yes</b></button>
				</div>
			</form>
			<br><br>
		</div>		
	</div>
</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block body %}
<div class="row">
	<div class="col l10 offset-l1 m11 s12">
		<div class="card-panel" style="opacity: 1;">
			<div class="row">
				<a href="{% url 'blog:user_post' pk=post.author.pk name=post.author.first_name %}">
					<img src="{{post.author.profile.img.url}}" align="left" class="responsive-img circle" style="margin-right: 40px; margin-bottom: 20px;margin-left: 20px;margin-top: 10px;">
				</a>
				<h2 class="josefin">{{post.title|title}}</h2>
				<h5 class="josefin blue-text right-align">- {{post.author.first_name}} {{post.author.last_name}}</h5>
				<p class="right-align cursive">{{post.created_on}}</p>
			</div>
			<p><pre class="cursive">{{post.content}}</pre></p>
			
			
		</div>
		{% if user == post.author %}
		<a href="{% url 'blog:edit' pk=post.pk %}" class="btn btn-floating white">
		<i class="material-icons black-text tooltipped" data-tooltip="Edit" data-position="top">create</i>
		</a>
		<a href="{% url 'blog:delete' pk=post.pk  %}" class="btn btn-floating white ">
		<i class="material-icons black-text tooltipped" data-tooltip="Delete" data-position="top">delete</i>
		</a>
		{% endif %}
	</div>
</div>



{% endblock %}

blog/templates/blog/user_post.html
{% extends 'blog/base.html' %}

{% block body %}


<div class="row">
	<div class="col l10 offset-l1 m11 s12 card-panel" style="opacity: 1;">
		<div class="row ">
			<img src="{{author.profile.img.url}}" align="left" class="responsive-img circle" style="margin-right: 40px; margin-bottom: 20px;margin-left: 20px;margin-top: 30px;">
			<br><br>
			<h3 class="cursive" style="margin-top: 30px;">{{author.first_name}} {{author.last_name}}</h3>
			<p>{{author.email}}</p>
		</div>
		<ul class="collapsible popout">
			{% for post in post_list %}
				<li>
					<div class="collapsible-header blue lighten-4">
						{{post.title|title}}<br>
						{{post.created_on}}
					</div>
					<div class="collapsible-body">
						<p class="cursive">{{post.content|linebreaksbr|truncatechars:100}}</p>
						<a href="{% url 'blog:detail' pk=post.pk  author=post.author.first_name %}" 
						class="btn blue lighten-4 black-text">View Article</a>
					</div>
				</li>
			{% endfor %}
		</ul>
		<br>
	</div>
</div>

{% if user.is_authenticated %}
	<div class="fixed-action-btn">
	<a href="{% url 'blog:new_post' %}" class="btn-floating btn-large white pulse">
			<i class="material-icons black-text tooltipped" data-tooltip="New Post" data-position="left">create</i>
	</a>
	</div>
	{% endif %}

{% if is_paginated %}
	<div class="center">
	<ul class="pagination ">
		{% if page_obj.has_previous %}
			<li class="transparent ">
				<a href="?page={{page_obj.previous_page_number}}" class="circle white black-text">
					&lsaquo;
				</a>
			</li>
		{% endif %}
		{% for num in page_obj.paginator.page_range %}
			{% if page_obj.number == num %}
				<li class="active transparent">
					<a href="?page={{num}}" class="circle black white-text">{{num}}</a>
				</li>
			{% else %}
				<li class=" transparent black-text">
					<a href="?page={{num}}" class="circle white">{{num}}</a>
				</li>
			{% endif %}
		{% endfor %}
			{% if page_obj.has_next %}
			<li class="transparent ">
				<a href="?page={{page_obj.next_page_number}}" class="circle white black-text">
					&rsaquo;
				</a>
			</li>
		{% endif %}
	</ul>
	</div>
{% endif %}


{% endblock %}